#
# Run `conda build .` to build this package
#

package:
  name: "lsst-numpy-eups-configs"
  version: "0.0.3"

source:
  git_rev: "c1bdd73fbef02df5b68128b4c309be514756acb9"
  git_url: "https://github.com/LSST/numpy"


build:
  number: 0
  string: "0"
#  binary_relocation: false

requirements:
  build:
    - eups >=2.0.2
    - gcc ==4.8.5                   # [not osx]
    - lsst-python-eups-configs ==0.0.5
    - nomkl                         #
    - numpy >=1.10.4
    - patchelf ==0.8                # [not osx]
    - python 2.7.*

  run:
    - eups >=2.0.2
    - libgcc >=4.8.5                # [not osx]
    - lsst-python-eups-configs ==0.0.5
    - nomkl                         #
    - numpy >=1.10.4

about:
  home: "https://github.com/LSST/numpy"
#  license: GPLv2
#  summary: A version manager tracking product dependencies
